# QoS overrides for rosbag replay

/run_session:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 10

/vehicle_plotter/state:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 10
