allow_camera_fallback_near: false
camera_debug: false
camera_debug_n_frames: 3
camera_range_m: 10
camera_rate_hz: 15.0
cone_memory_enabled: true
controller: stanley
cuda: true
cuda_runtime_ld_library_path: /home/aleks/ros2_ws/cuda_runtime/lib
cudnn_ld_library_path: /home/aleks/ros2_ws/cudnn_py/nvidia/cudnn/lib
headless: false
lidar_enabled: true
lidar_pipeline: scan2d
measure: false
measurement_config: /home/aleks/ros2_ws/install/sim_car/share/sim_car/config/sensor_config.yaml
monocular_bbox_height_offset_px: 1.3075
opencv_ld_library_path: /home/aleks/ros2_ws/opencv_local/lib
opencv_pythonpath: /home/aleks/ros2_ws/opencv_local/lib/python3.10/dist-packages
perception_queue_size: 8
perception_rate_hz: 60.0
planner: single_boundary
planner_odom_delay_ms: 20.0
planner_odom_lag_compensation_ms: 20.0
planner_rate_hz: 60.0
prefer_lidar_if_camera_missing_far: true
rviz: true
rviz_config: ''
rviz_profile: planner
sensor_pipeline: true
sensors_render_engine: ogre2
spawn_x: 0.0
spawn_y: -10.0
spawn_yaw: 1.5708
spawn_z: 0.0
steering: false
stereo: false
track: skidpad
update_rate_hz: 180.0
world: /home/aleks/ros2_ws/install/sim_car/share/sim_car/worlds/skidpad.world
yolo_conf_threshold: 0.25
yolo_enabled: true
yolo_input_size: 960
yolo_iou_threshold: 0.45
yolo_model_path: /home/aleks/ros2_ws/install/sim_car/share/sim_car/yolo/weights/best.pt
yolo_prefer_cuda: true
yolo_ultralytics_pythonpath: /home/aleks/ros2_ws/yolo_pt_venv/lib/python3.10/site-packages
