#!/usr/bin/env python

import sys

from steering_gui.EUFSRobotSteeringGUI import EUFSRobotSteeringGUI
from rqt_gui.main import Main

plugin = 'steering_gui.EUFSRobotSteeringGUI.EUFSRobotSteeringGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
