single_boundary_planner_node:
  ros__parameters:
    filtering:
      max_cone_range_m: 20.0
    midline_memory:
      horizon_m: 20.0
    stanley:
      lookahead_idx_offset: 1
    pure_pursuit:
      lookahead_m: 2.0
      min_lookahead_m: 0.5
      max_lookahead_m: 10.0
    speed_control:
      speed_max_mps: 4.17
