spawn:
  spawn_x: -13.6758
  spawn_y: 10.4753
  spawn_yaw: 0

speed_control:
  speed_min_mps: 0.0
  speed_max_mps: 0.0
  curvature_speed_gain: 4.0
  lowpass_speed_alpha: 0.15

lap_tracking:
  auto_suspend_after_laps: 1
